### ISSUE TITLE
Code review - Week 3 revisions

### ISSUE THREAD

**Issue by mullenlucas** [sntgopl/Porfolio#12]
Hello Santiago, very good code ! The javascript works really good

One suggestion I would like to make, which is a tiny detail, is sometimes when assigning classes to ul or li tags, it would be perhaps cleaner to manipulate their css with sub-classes instead of giving them specific classes, so as not to overload the html with new classes.

So for example, in this line:
https://github.com/sntgopl/Porfolio/blob/ced945a98bd0e3779707882c85fabe8f0b78c0a2/index.html#L49

could be something like:
```
.introinfo ul {
   *styling*
}

.introinfo ul li {
   *styling*
}
```

All in all great code !

**Comment by RodChak** [comment]
Great Work Santiago!👌👌💯 Looks awesome, just a quick suggestion, you can add the navigation bar at the very bottom of the screen just to make your portfolio look the same as the template given. I've attached a screenshot of the template below
![image](https://user-images.githubusercontent.com/97179349/179776727-5d63866b-3104-4279-8a82-ce2a434fca91.png)

**Comment by sntgopl** [comment]
Thank you for your comments guys. Will take them into account.
