### ISSUE TITLE
issues related to deploying your website into github page

### ISSUE THREAD

**Issue by mohamed20163858** [sntgopl/Porfolio#8]
your code is great, has a nice view and all the functionalities work properly but here are some of the issues you need to work with:-
1) I think it will be good  to include your Github page inside your README.md and try to not just simply copy and paste your link there instead use the markdown syntax to embed your link by typing it  like that [fancy name] (your actual link) it will increase the readability of your README.md file
2) according to the rules of GitHub I think there is an easier way to follow to deploy your site just go to settings inside your repo choose pages in the left sidebar then choose the branch you are currently working with then click save after that wait 3 minutes at least then refresh your page your deploy will be posted in the page with the green mark

**Comment by sntgopl** [comment]
Very much thanks on your review and will take your suggestions into consideration. Thank you.
